# -*- coding: utf-8 -*-
"""Titanic - Machine Learning from Disaster - H2o.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_xbNqQF6LGpzHiZ4uKU6OCG73czzZo9
"""

!pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

# Load common libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import numpy as np

# Framework libraries
import h2o
from h2o.automl import H2OAutoML
h2o.init()

# Reading dataset
data = pd.read_csv("train.csv")
data["CabinNoCabin"] = np.where(data["Cabin"].isnull(), "No Cabin", "Cabin")
data["survived"] = np.where(data["Survived"] == 1, "yes", "no")
# data["Age"] = data["Age"].fillna(data["Age"].mean())
data.drop(["PassengerId", "Name", "Ticket", "Cabin", "Survived"], axis = 1, inplace = True)
data.head()

# Split data
train_data, test_data = train_test_split(data, test_size = 0.2)

# Create datasets in the right form for H2O
train_data = h2o.H2OFrame(train_data)
test_data = h2o.H2OFrame(test_data)

# Role definition
X = train_data.columns
y = 'survived'
X.remove(y)

# Set up framework
automl = H2OAutoML(max_runtime_secs=300, seed = 1)

# Fit model
automl.train(x = X, y=y, training_frame=train_data)

lb = automl.leaderboard
lb.head(rows = lb.nrows)

# Show best model
best_model = automl.leader
best_model

# Evaluate performance on both traind and test set
performance_train = best_model.model_performance(test_data = train_data)
performance_test = best_model.model_performance(test_data = test_data)

# Report statistics
print("Train Accuracy score: ", performance_train.accuracy())
print("Train AUC score: ", performance_train.auc())

print("Test Accuracy score: ", performance_test.accuracy())
print("Test AUC score: ", performance_test.auc())

# Save the best model
model_path = '/content/drive/MyDrive/Colab Notebooks/Kaggle/h2omodel_Titanic01'
h2o.save_model(model=best_model, path = model_path, force = True)

print(automl.feature_importance(data))

"""# PREDICTION"""

# Reading new data
new_data = pd.read_csv("test.csv")
new_data["CabinNoCabin"] = np.where(new_data["Cabin"].isnull(), "No Cabin", "Cabin")
new_data.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis = 1, inplace = True)

new_data = h2o.H2OFrame(new_data)

# Read saved model
loaded_model = h2o.load_model('/content/drive/MyDrive/Colab Notebooks/Kaggle/h2omodel_Titanic01/StackedEnsemble_AllModels_5_AutoML_2_20251006_24550')
loaded_model

# Predict new dataset
prediction = loaded_model.predict(new_data)
prediction

h2o.export_file(prediction, "survived01_h2omodel.csv")

"""# FINDING THE CUT-OFF POINT

y_def = test_data.as_data_frame(use_pandas=True)["survived"]
y_true = np.where(y_def == "yes", 1, 0)
y_true = pd.DataFrame(y_true)
y_true["survived"] = y_true[0]
y_true.drop([0], axis = 1, inplace = True)
y_true
"""

# df = pd.read_csv("test.csv")
# df

h2o.shutdown()