# -*- coding: utf-8 -*-
"""Titanic autoGluon - Machine Learning from Disaster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieBfnSLbVqDsZcurymhzIK1SizCelOnj
"""

!pip install autogluon --extra-index-url https://download.pytorch.org/whl/cpu

import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_squared_error, f1_score
from sklearn.model_selection import train_test_split
import math

# Framework Library
from autogluon.tabular import TabularDataset, TabularPredictor

# Reading dataset
data = pd.read_csv("train.csv")
data["CabinNoCabin"] = np.where(data["Cabin"].isnull(), "No Cabin", "Cabin")
data["survived"] = np.where(data["Survived"] == 1, "yes", "no")
# data["Age"] = data["Age"].fillna(data["Age"].mean())
data.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis = 1, inplace = True)
data.head()

# Split data
train_data, test_data = train_test_split(data, test_size = 0.2)

# Create datasets in the right format for autogluon
train_data = TabularDataset(train_data)
test_data = TabularDataset(test_data)

# Set up framework
automl = TabularPredictor(
    label = "survived",
    # eval_metric = "accuracy, log_loss, roc_auc",
    path = "/content/drive/MyDrive/Colab Notebooks/Kaggle/agmodel_Titanic01"
)

# Fit model
automl.fit(train_data, time_limit=300, num_cpus=8)

# show leaderboard
automl.leaderboard(test_data, silent = True)

automl.evaluate(train_data)

automl.evaluate(test_data)

print(automl.feature_importance(data))

"""# PREDICTION"""

# Reading new data
new_data = pd.read_csv("test.csv")
new_data["CabinNoCabin"] = np.where(new_data["Cabin"].isnull(), "No Cabin", "Cabin")
new_data.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis = 1, inplace = True)

new_data = TabularDataset(new_data)
new_data

# Load saved model
model_path = "/content/drive/MyDrive/Colab Notebooks/Kaggle/agmodel_Titanic01"
predictor = TabularPredictor.load(model_path)
predictor

# Make predictions on the new dataset
predictions = predictor.predict_proba(new_data)
predictions

predictions.to_csv("survived.csv")

"""# FINDING THE CUT-OFF POINT"""

y_true = test_data["Survived"]  # ground truth
y_proba = predictor.predict_proba(test_data)[1]  # probas for class 1

thresholds = np.linspace(0,1,101)
f1_scores = [f1_score(y_true, y_proba >= t) for t in thresholds]

best_t = thresholds[np.argmax(f1_scores)]
print("Best threshold:", best_t)

df = pd.read_csv("test.csv")
df